import { Card } from "@/components/ui/card";
import { SEO } from "@/components/SEO";

const TermsOfService = () => {
  return (
    <div className="min-h-dvh bg-background">
      <SEO title="Terms of Use" description="Read Kaizen Afrika's Terms of Use. Understand your rights and responsibilities when using the Kaizen Afrika platform, including invoicing and AI features." keywords="Kaizen Afrika terms of use, terms of service, user agreement, platform terms" url="/terms-of-service" />

      <main className="container max-w-4xl px-4 py-8 md:py-16">
        <div className="mb-8 md:mb-12">
          <h1 className="font-vollkorn text-3xl md:text-5xl font-bold mb-4">Terms of Use</h1>
          <p className="text-muted-foreground text-sm md:text-base">
            Last Updated: June 2, 2026 &nbsp;·&nbsp; Effective Date: June 2, 2026
          </p>
        </div>

        <Card className="p-6 md:p-8 space-y-8">

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using the Kaizen Afrika platform ("Kaizen Afrika," "we," "us," or "our"), including Kaizen Studio, Kaizen Invoice, our AI (Kira), and any other current or future products or features provided by us, you agree to be bound by these Terms of Use ("Terms"). If you are using the platform on behalf of a brand, agency, or corporate entity, you represent that you have the authority to bind that entity to these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Kaizen Afrika provides infrastructure to scale your business operations. The platform includes our central operating system (Kaizen Studio), professional invoicing (Kaizen Invoice), customizable public profiles (Kaizen Link), an artificial intelligence tool (Kira), and any other products, tools, or services we may introduce over time.
            </p>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">3. Account Registration &amp; Tiered Access</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <div>
                <p className="font-semibold text-foreground mb-1">Account Security</p>
                <p>You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">4. Artificial Intelligence (Kira) Disclaimer</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>Kaizen Afrika integrates proprietary AI tools (Kira) to assist in structuring deals, generating document templates, and analyzing project scope.</p>
              <div>
                <p className="font-semibold text-foreground mb-1">No Legal or Financial Advice</p>
                <p>Kira is a technological tool, not a licensed attorney or financial advisor. Any documents, agreements, or scope of work files generated by Kira must be independently reviewed by the user.</p>
              </div>
              <div>
                <p className="font-semibold text-foreground mb-1">User Liability</p>
                <p>Kaizen Afrika assumes no liability for the enforceability, accuracy, or legal standing of documents generated using our AI tools.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">5. Invoicing and Independent Tax Compliance</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <p>Kaizen Invoice allows users to generate professional billing documents and receipts.</p>
              <div>
                <p className="font-semibold text-foreground mb-1">No Tax Agency</p>
                <p>Kaizen Afrika is a software infrastructure provider. We are not a certified tax agent, accounting firm, or government integration partner.</p>
              </div>
              <div>
                <p className="font-semibold text-foreground mb-1">User Responsibility</p>
                <p>You are strictly and solely responsible for your own tax compliance, VAT reporting, and ensuring that your generated invoices meet local regulatory requirements. Kaizen Afrika assumes no liability for tax fraud, audit penalties, or rejected claims resulting from your financial operations or the use of our infrastructure.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">6. Subscriptions and Payments</h2>
            <div className="text-muted-foreground leading-relaxed space-y-3">
              <div>
                <p className="font-semibold text-foreground mb-1">Billing</p>
                <p>Pro and Business tier subscriptions are billed automatically according to the selected billing cycle.</p>
              </div>
              <div>
                <p className="font-semibold text-foreground mb-1">Refunds</p>
                <p>All subscription fees are non-refundable unless legally mandated by local jurisdiction.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, Kaizen Afrika Ventures Limited, its founders, and employees shall not be liable for any indirect, incidental, special, or consequential damages, including lost profits, lost revenue, or loss of data resulting from the use or inability to use the platform.
            </p>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">8. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of the Republic of Kenya. Any disputes arising out of these Terms shall be subject to the exclusive jurisdiction of the courts in Nairobi, Kenya.
            </p>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">9. Modifications to the Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to update, modify, or replace these Terms at any time at our sole discretion. If a revision is material, we will provide reasonable notice prior to any new terms taking effect via an announcement on the platform or via email. Your continued use of the Kaizen Afrika platform following the posting of any changes constitutes explicit acceptance of those changes.
            </p>
          </section>

          <section>
            <h2 className="font-vollkorn text-2xl md:text-3xl font-bold mb-4">Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed">
              For any questions regarding these Terms, please contact our team:
            </p>
            <div className="mt-4 p-4 bg-muted/50 rounded-lg">
              <p className="font-poppins text-sm">
                <strong>Email:</strong> hi@kaizenafrika.app<br />
                <strong>Location:</strong> Nairobi, Kenya
              </p>
            </div>
          </section>

        </Card>
      </main>
    </div>
  );
};

export default TermsOfService;
